[package]
name = "slate-pl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "~0.4"
xml-rs = "~0.8"
textwrap = "~0.14.2"