[package]
name = "slate-pl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "^0.8"
textwrap = "^0.14.2"
tempdir = "^0.3.7"
# lazy_static = "^1.4.0"
# hex = "^0.4"
# base64 = "^0.13"